### ISSUE TITLE
React 16 Compatibility

### ISSUE THREAD

**Issue by mbgame** [CarMax/react-cursor-zoom#8]
Error on prop-types for React 16

**Comment by Jarlotee** [comment]
Hey there @mbgame, that is a pretty generic error message. Could you fill me in on how you are using it react-cursor-zoom in your project?

It should look something like 
```jsx
<CursorZoom
  image={{
    src: "img/beach-small.jpg",
    width: 400,
    height: 300
  }}
  zoomImage={{
    src: "img/beach-large.jpg",
    width: 1600,
     height: 1200
  }}
  cursorOffset={{ x: 80, y: -80 }}
/>
```

Also double check that you are not passing a null image or zoomimage prop.

**Comment by mbgame** [comment]
hi jarlotee
i use it like this :'
<div className='productImg'>
				<CursorZoom
                image={{
                    src: this.props.fish.Image,
                    width: 400,
                    height: 300
                }}
                zoomImage={{
                    src: this.props.fish.Image,
                    width: 1600,
                    height: 1200
                }}
                cursorOffset={{ x: 80, y: -80 }}
            	/>
			</div>
and prop is the address of image
i get this error

./node_modules/react-cursor-zoom/lib/magnifier.js
D:/react-project/mahifarm/node_modules/react-cursor-zoom/lib/magnifier.js:134
  131 | Magnifier.displayName = 'CursorZoom';
  132 | Magnifier.propTypes = {
  133 |   // the size of the magnifier window
> 134 |   size: _react2.default.PropTypes.number.isRequired,
  135 |   // x position on screen
  136 |   x: _react2.default.PropTypes.number.isRequired,
  137 |   // y position on screen

**Comment by Jarlotee** [comment]
My guess is you are using React at v15.5.0 or later? PropTypes were moved out of React and into their own package. What version of react are you using?

**Comment by mbgame** [comment]
v 8.11.3

**Comment by mbgame** [comment]
"dependencies": {
    "material-icons-react": "^1.0.4",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-image-magnifiers": "^1.0.5",
    "react-scripts": "3.0.1"
  }

**Comment by Jarlotee** [comment]
Gotcha, we will need to update this library to be react 16 compatible, stay tuned

**Comment by mbgame** [comment]
ok i m waitnig for u
thx for your response

**Comment by kuckboy1994** [comment]
How is the progress now?

**Comment by ansario** [comment]
Hey @mbgame and @kuckboy1994, please give it a try now with the latest version.
